name: thierry
favicon: null
layout_spectrum: 0
typography_spectrum: 0.28293
title: 'Thierry De Vynck, Creative Strategy'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000004'
    - '#c0c3cc'
    - '#6f777a'
    - '#b21841'
  brandStrength: 0.4375
  lightness: 0.8125
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
